substitutions:
  comment: "Camera1 (камера с индикатором и подсветкой)
            на S3V1 (ESP32-S3 N16R8 CAM OV5640)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    ref: 1.2.1
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml

  units: !include units/camera1.yaml

  # Camera1                                                 S3V1
  # Камера                  (esp32_camera)                  +
  # Индикатор камеры        (light_indicator)               +
  # Подсветка               (light_flash)                   +

  boards:
    url: https://github.com/ivanych/esphome-boards
    ref: 4.0.0
    files:
      # Плата S3V1
      - s3v1.yaml
    #!include ../esphome-boards/s3v1.yaml

# На S3V1 есть кнопка, но для камеры она не нужна - удаляем
binary_sensor:
  - id: !remove binary_sensor_button_1
