substitutions:
  friendly_name: 'Relay-1C-C1'
  comment: "Реле с одним каналом на C1 (Luatos CORE-ESP32)"
  timezone: "Europe/Moscow"
  project_author: "ivanych"
  project_version: '1.0.0'

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
    ref: 0.3.0

  units: github://ivanych/esphome-units/relay_1c.yaml@3.0.0
  #units: !include ../esphome-units/relay_1c.yaml

  boards: github://ivanych/esphome-boards/c1.yaml@1.1.0
  #boards: !include ../esphome-boards/c1.yaml

# Принудительное создание канала реле на c1
output:
  - platform: gpio
    id: output_relay
    pin:
      number: 11
