substitutions:
  friendly_name: 'Relay4-SP316'
  comment: "Реле с одним каналом, кнопкой и светодиодом на SP316 (Sonoff POWR316)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
    ref: 1.0.0

  units: github://ivanych/esphome-units/relay4.yaml@4.1.0
  #units: !include ../esphome-units/relay4.yaml

  boards: github://ivanych/esphome-boards/sp316.yaml@1.6.0
  #boards: !include ../esphome-boards/sp316.yaml
