substitutions:
  comment: "Relay5 (реле с одним каналом, светодиодом, кнопкой и выключателем)
            на C1 (Luatos CORE-ESP32)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    ref: 1.2.1
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
      - is_boot.yaml

  units: github://ivanych/esphome-units/relay5.yaml@6.0.0
  #units: !include ../esphome-units/relay5.yaml

  # Relay5                                  C1
  # реле1         (output_relay_1)
  # светодиод1    (output_led_1)            *
  # кнопка1       (binary_sensor_button)    *
  # выключатель1  (binary_sensor_switch_1)

  boards:
    url: https://github.com/ivanych/esphome-boards
    ref: 3.0.1
    files:
      # Плата C1
      - c1.yaml

      # реле1
      - path: int/output_relay.yaml
        vars:
          pin:
            number: 6
            inverted: true
          exposed: true

      # выключатель1
      - path: int/binary_sensor_switch.yaml
        vars:
          pin:
            number: 10
          exposed: true
