substitutions:
  friendly_name: 'Relay-1M-SMR4'
  comment: "Реле с одним каналом, кнопкой и внешним выключателем на SMR4 (Sonoff MINIR4)"
  timezone: "Europe/Moscow"
  project_author: "ivanych"
  project_version: '1.0.0'

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
    ref: 0.3.0

  units: github://ivanych/esphome-units/relay_1m.yaml@3.0.0
  #units: !include ../esphome-units/relay_1m.yaml

  boards: github://ivanych/esphome-boards/smr4.yaml@1.1.0
  #boards: !include ../esphome-boards/smr4.yaml
