# Двухканальное реле с измерением мощности на основе Sonoff DUALR3

substitutions:
  device_name: 'relay2p'
  device_board: 'sdr3'
  device_number: '00'               # переопределяется выше
  friendly_name: 'Relay2P SDR3 #00' # переопределяется выше
  comment: "Реле Sonoff DUALR3"
  timezone: "Europe/Moscow"
  project_author: "ivanych"
  project_version: '0.2.0'

esphome:
  name: ${device_name}-${device_board}-${device_number}
  friendly_name: ${friendly_name}
  comment: ${comment}
  project:
    name: ${project_author}.${device_name}-${device_board}-${device_number}
    version: ${project_version}

packages:
  boards: github://ivanych/esphome-boards/sdr3.yaml@0.2.0
  #boards: !include ../esphome-boards/sdr3.yaml

  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
    ref: 0.0.1

  units: github://ivanych/esphome-units/relay2p.yaml@0.2.0
  #units: !include ../esphome-units/relay2p.yaml
