substitutions:
  comment: "Relay5 (реле с одним каналом, светодиодом, кнопкой и выключателем)
            на SMR4 (Sonoff MINIR4)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
      - is_boot.yaml
      # Плата SMR4 не имеет отдельного статусного светодиода, придётся
      # добавить его, совместив со светодиодом на плате.
      - status_led.yaml
    ref: 1.2.1

  units: github://ivanych/esphome-units/relay5.yaml@6.0.0
  #units: !include ../esphome-units/relay5.yaml

  boards: github://ivanych/esphome-boards/smr4.yaml@3.0.1
  #boards: !include ../esphome-boards/smr4.yaml
