substitutions:
  comment: "Relay4 (реле с одним каналом, светодиодом и кнопкой)
            на C1 (Luatos CORE-ESP32)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    files:
      #- common.yaml
      - sensors.yaml
      - time.yaml
    ref: 1.1.0
  com: !include ../esphome-common/common.yaml
  is_boot: !include ../esphome-common/is_boot.yaml

  units: github://ivanych/esphome-units/relay4.yaml@6.0.0
  #units: !include ../esphome-units/relay4.yaml

  boards: github://ivanych/esphome-boards/c1.yaml@3.0.1
  #boards: !include ../esphome-boards/c1.yaml

  # Relay4                                C1
  # реле1       (output_relay_1)
  # светодиод1  (output_led_1)            *
  # кнопка1     (binary_sensor_button_1)  *

  # реле1
  output_relay_1: !include
    file: ../esphome-boards/int/output_relay.yaml
    vars:
      pin:
        number: 6
        inverted: true
      exposed: true
