# Реле на основе Sonoff MINIR4

substitutions:
  device_name: 'relay'
  device_board: 'smr4'
  device_number: '00'             # переопределяется выше
  friendly_name: 'Relay SMR4 #00' # переопределяется выше
  comment: "Реле Sonoff MINIR4"
  timezone: "Europe/Moscow"
  project_author: "ivanych"
  project_version: '0.1.0'

esphome:
  name: ${device_name}-${device_board}-${device_number}
  friendly_name: ${friendly_name}
  comment: ${comment}
  project:
    name: ${project_author}.${device_name}-${device_board}-${device_number}
    version: ${project_version}

packages:
  boards: github://ivanych/esphome-boards/smr4.yaml@1.0.0
  #boards: !include ../esphome-boards/smr4.yaml

  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
    ref: 0.0.1

  units: github://ivanych/esphome-units/relay.yaml@1.0.0
  #units: !include ../esphome-units/relay.yaml
