substitutions:
  comment: "Relay7 (реле с двумя каналами, одной кнопкой и двумя выключателями)
            на SDR3 (Sonoff DUALR3)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    ref: 1.2.1
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
      - is_boot.yaml

  units: github://ivanych/esphome-units/relay7.yaml@6.0.0
  #units: !include ../esphome-units/relay7.yaml

  # Relay7                                  SDR3
  # реле1         (output_relay_1)          *
  # реле2         (output_relay_2)          *
  # кнопка1       (binary_sensor_button)    *
  # выключатель1  (binary_sensor_switch_1)  *
  # выключатель2  (binary_sensor_switch_2)  *

  boards:
    url: https://github.com/ivanych/esphome-boards
    ref: 3.0.1
    files:
      # Плата SDR3
      - sdr3.yaml
