substitutions:
  comment: "Relay4 (реле с одним каналом, светодиодом и кнопкой)
            на SP316 (Sonoff POWR316)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
      - is_boot.yaml
    ref: 1.2.1

  units: github://ivanych/esphome-units/relay4.yaml@6.0.0
  #units: !include ../esphome-units/relay4.yaml

  boards: github://ivanych/esphome-boards/sp316.yaml@3.0.1
  #boards: !include ../esphome-boards/sp316.yaml
