substitutions:
  device_name: 'relay'
  device_board: 'smr4'
  comment: "Реле Sonoff MINIR4"
  timezone: "Europe/Moscow"
  project_author: "ivanych"
  project_version: '0.1.0'

packages:
  boards: github://ivanych/esphome-boards/smr4.sonoff_minir4.yaml@0.1.0
  #boards: !include esphome-boards/smr4.sonoff_minir4.yaml

  common:
    url: https://github.com/ivanych/esphome-common
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
    ref: 0.0.1

  units: github://ivanych/esphome-units/relay.yaml@0.1.0
  #units: !include esphome-units/relay.yaml
