substitutions:
  comment: "Relay4 (реле с одним каналом, светодиодом и кнопкой)
            на SP316 (Sonoff POWR316)"

packages:
  common:
    url: https://github.com/ivanych/esphome-common
    ref: 1.2.1
    files:
      - common.yaml
      - sensors.yaml
      - time.yaml
      - is_boot.yaml

  units: github://ivanych/esphome-units/relay4.yaml@6.0.0
  #units: !include ../esphome-units/relay4.yaml

  # Relay4                                  SP316
  # реле1         (output_relay_1)          *
  # светодиод1    (output_led_1)            *
  # кнопка1       (binary_sensor_button)    *

  boards:
    url: https://github.com/ivanych/esphome-boards
    ref: 3.0.1
    files:
      # Плата SP316
      - sp316.yaml
