# Камера со светодиодом
#
# Управляемые объекты:
#   - нет
# Требует управляемые объекты:
#   - Камера                    (esp32_camera)
#   - Cветодиод                 (output_led)

substitutions:
  number: 1
  resolution: 800x600
  jpeg_quality: 10

esp32_camera:

  # Image Settings:
  resolution: ${resolution}
  jpeg_quality: ${jpeg_quality}

  # Добавляем поведение камере — при запуске трансляции включается светодид.
  # Хорошо бы ещё сделать мигание светодиодом при захвате снимка
  # по триггеру on_image. Но триггер on_image сделан странно —
  # он срабатывает и при трансляции, конфликтуя с триггером on_stream_start.
  # Если сделать мигание в on_image, то светодиод будет непрерывно мигать
  # при трансляции, хотя согласно on_stream_start он должен просто гореть.
  on_stream_start:
    - output.turn_on: output_led_${number}
  on_stream_stop:
    - output.turn_off: output_led_${number}

# Это временный костыль, чтобы показать настройки resolution и jpeg_quality,
# которые не работают через интерфейс из-за бага в esphome
# (https://github.com/esphome/issues/issues/5499)
text_sensor:
  - platform: template
    name: "Camera ${number} (resolution)"
    icon: mdi:quality-high
    entity_category: diagnostic
    lambda: 'return {"${resolution}"};'
  - platform: template
    name: "Camera ${number} (jpeg_quality)"
    icon: mdi:aspect-ratio
    entity_category: diagnostic
    lambda: 'return {"${jpeg_quality}"};'
