# Индикатор
#
# Управляемые объекты:
#   - Индикатор (lite.indicator)
# Требует управляемые объекты:
#   - source: light
#   - target: [turn_on, turn_off]

substitutions:
  number: 1
  name: "Indicator ${number}"
  source:
    id: null
    #number: 1
  target:
    id: null
    #number: 1

light:
  - id: !extend ${source.id}_${source.number}
    on_turn_on:
      - logger.log:
          format: "▶ ${source.id}_${source.number}.on_turn_on"
          tag: "light"
      - lambda: 'id(${target.id}_${target.number}).turn_on();'
      - logger.log:
          format: "  ${target.id}_${target.number}.turn_on"
          tag: "light"
    on_turn_off:
      - logger.log:
          format: "▶ ${source.id}_${source.number}.on_turn_off"
          tag: "light"
      - lambda: 'id(${target.id}_${target.number}).turn_off();'
      - logger.log:
          format: "  ${target.id}_${target.number}.turn_off"
          tag: "light"
