# Подсветка
#
# Управляемые объекты:
#   - Подсветка (light_flash)
# Требует управляемые объекты:
#   - Подсветка (light_flash)

substitutions:
  number: 1
  name: "Flash ${number}"

light:
  # Подсветка
  - id: !extend light_flash_${number}
    name: ${name}
