# Индикатор камеры
#
# Управляемые объекты:
#   - нет
# Требует управляемые объекты:
#   - Камера                            (esp32_camera)
#   - Выходной пин индикатора           (output_light_indicator)

substitutions:
  number: 1

esp32_camera:
  # Добавляем поведение камере — при запуске трансляции включается светодид.
  # Хорошо бы ещё сделать мигание светодиодом при захвате снимка
  # по триггеру on_image. Но триггер on_image сделан странно —
  # он срабатывает и при трансляции, конфликтуя с триггером on_stream_start.
  # Если сделать мигание в on_image, то светодиод будет непрерывно мигать
  # при трансляции, хотя согласно on_stream_start он должен просто гореть.
  on_stream_start:
    - output.turn_on: output_light_indicator_${number}
  on_stream_stop:
    - output.turn_off: output_light_indicator_${number}
