# Веб-сервер камеры
#
# Управляемые объекты:
#   - нет
# Требует управляемые объекты:
#   - Камера                            (esp32_camera)

substitutions:
  number: 1

esp32_camera_web_server:
  # Добавляем поведение камере — веб-сервер для прямого доступа к камере
  - port: 80
    mode: stream
  - port: 81
    mode: snapshot
