# Camera1
# Камера с индикатором и подсветкой

substitutions:
  friendly_unit_name: "Camera1"

packages:
  # Камера
  camera: !include
    file: sub/camera.yaml
    vars:
      name: "Camera"

  # Индикатор камеры
  indicator: !include
    file: sub/camera/indicator.yaml

  # Подсветка
  flash: !include
    file: sub/light_flash.yaml
    vars:
      name: "Flash"

  # ---

  # Настройки камеры
  settings: !include
    file: sub/camera/settings.yaml

  # Веб-сервер камеры
  web_server: !include
    file: sub/camera/web_server.yaml
